services:
    tdoescher\IfCookieBundle\EventListener\DataContainer\AddPalleteCallback:
        autoconfigure: true
    tdoescher\IfCookieBundle\EventListener\GetContentElementListener:
        autoconfigure: true
